APPLY_FIXES: all
DISABLE_LINTERS:
  - JSON_JSONLINT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_LYCHEE
FAIL_IF_UPDATED_SOURCES: true
GITHUB_STATUS_REPORTER: true
PYTHON_DEFAULT_STYLE: ruff
REPOSITORY_CHECKOV_ARGUMENTS: --hard-fail-on HIGH
REPOSITORY_KICS_ARGUMENTS: --fail-on critical,high
REPOSITORY_SEMGREP_ARGUMENTS: --exclude *.lock
REPOSITORY_SEMGREP_RULESETS: [p/default]
SARIF_REPORTER: true
VALIDATE_ALL_CODEBASE: false
