APPLY_FIXES: all
DISABLE_LINTERS:
  - JSON_JSONLINT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
FAIL_IF_UPDATED_SOURCES: true
FILTER_REGEX_EXCLUDE: (\.lock$|lock\.[^.]+$)
GITHUB_STATUS_REPORTER: true
PYTHON_DEFAULT_STYLE: ruff
REPOSITORY_SEMGREP_RULESETS: [p/default]
SARIF_REPORTER: true
VALIDATE_ALL_CODEBASE: false
