[build-system]
requires = ["poetry-core>=2.0,<3.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "mf_torch"
version = "0.1.0"
description = "Matrix Factorization Recommender Models in PyTorch with MovieLens"
authors = [{ name = "YuXuan Tay", email = "wyextay@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
  "bentoml~=1.3",
  "flaml[blendsearch]~=2.3",
  "jsonargparse[signatures]~=4.35",
  "lancedb>=0.19",
  "lightning~=2.5",
  "loguru>=0.7,<0.8",
  "mlflow~=2.19",
  "numpydantic~=1.6",
  "onnxscript>=0.2,<0.3",
  "onnxruntime~=1.20",
  "pandas~=2.2",
  "polars[pandas]~=1.19",
  "ray[data,train,tune]~=2.40",
  "tensorboard~=2.17",
  "torch~=2.5",
  "xxhash~=3.4",
]

[tool.ruff]
fix = true
src = [".", "src", "tests"]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",      # pydocstyle
  "E501",   # line-too-long
  "COM812", # missing-trailing-comma, conflicts with ruff formatter
  "ERA001", # commented-out-code
  "ISC001", # single-line-implicit-string-concatenation, conflicts with ruff formatter
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = [
  "S101", # assert
]
