[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mf-torch"
version = "0.1.0"
description = "Matrix Factorization Recommender Models in PyTorch with MovieLens"
authors = ["YuXuan Tay <wyextay@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
# python pinned to 3.11 due to ray
python = "^3.11,<3.12"
bentoml = "^1.2"
deltalake = ">=0.17,<0.19"
docarray = ">=0.40.0"
flaml = "^2.1"
lancedb = ">=0.8"
lightning = { extras = ["pytorch-extra"], version = "^2.3.3" }
loguru = ">=0.7"
mlflow = "^2.14"
mmh3 = "^4.1"
polars = { extras = ["pandas"], version = ">=0.20" }
ray = { extras = ["train", "tune"], version = "^2.32" }
tensorboard = "^2.17"
torch = "^2.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7"
ruff = ">=0.4"

[tool.ruff]
fix = true
src = [".", "src", "tests"]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstyle
    "E501",   # line-too-long
    "COM812", # missing-trailing-comma, conflicts with ruff formatter
    "ERA001", # commented-out-code
    "ISC001", # single-line-implicit-string-concatenation, conflicts with ruff formatter
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = [
    "S101", # assert
]
