name: automerge
on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  dependabot:
    permissions:
      contents: read
      pull-requests: write

    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2

      - name: log metadata
        run: echo "${DEPENDABOT_METADATA}"
        env:
          DEPENDABOT_METADATA: ${{ toJson(steps.metadata.outputs) }}

      - name: automerge
        if: ${{ !contains(steps.metadata.outputs.update-type, 'major' ) }}
        run: gh pr merge "${PR_NUMBER}" --auto --squash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

  pre-commit-ci:
    permissions:
      contents: read
      pull-requests: write

    if: ${{ github.actor == 'pre-commit-ci' }}
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        run: |
          gh pr edit "${PR_NUMBER}" --title "ci: ${PR_TITLE}"
          gh pr merge "${PR_NUMBER}" --auto --squash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
