name: ci

on:
  push:
    branches: [main]
    tags: ["**"]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  python:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1
      UV_NO_SYNC: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6

      - id: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5

      - run: |
          uv lock --check
          uv sync --locked
          uv pip list

      - if: ${{ success() || failure() }}
        run: uv run lightning fit --print_config

      - if: ${{ success() || failure() }}
        run: uv run bentoml_cli

      - if: ${{ failure() }}
        run: uv run python -m mf_torch.lightning

      - if: ${{ failure() }}
        run: uv run python -m mf_torch.data.lightning

      - if: ${{ failure() }}
        run: uv run data

  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:

      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - id: build
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6
        with:
          cache-from: ${{ env.GHCR_IMAGE_NAME }}:cache
          load: true

      - if: ${{ success() || failure() }}
        run: docker run "${IMAGE_ID}" uv pip list
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ success() || failure() }}
        run: docker run "${IMAGE_ID}" uv run lightning fit --print_config
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ success() || failure() }}
        run: docker run "${IMAGE_ID}" uv run bentoml_cli
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: docker run "${IMAGE_ID}" python -m mf_torch.lightning
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: docker run "${IMAGE_ID}" python -m mf_torch.data.lightning
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: docker run "${IMAGE_ID}" uv run data

        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - id: docker_metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ env.GHCR_IMAGE_NAME }}

      - if: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - if: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6
        with:
          cache-from: ${{ env.GHCR_IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.GHCR_IMAGE_NAME }}:cache,mode=max
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          annotations: ${{ steps.docker_metadata.outputs.annotations }}
          push: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
