name: scans
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  megalinter:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - id: megalinter
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter/flavors/python@e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # v8
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - if: ${{ success() || failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: megalinter-reports
          path: megalinter-reports

      - if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
          ref: ${{ github.head_ref && format('refs/heads/{0}', github.head_ref) || github.ref }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - if: ${{ failure() && steps.megalinter.outputs.has_updated_sources == 1 && github.event_name == 'pull_request' }}
        name: commit changes
        run: |
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git commit --all --message "${COMMIT_MESSAGE}"
          git push origin "HEAD:refs/heads/${GITHUB_HEAD_REF}"
        env:
          COMMIT_MESSAGE: "fix: apply megalinter fixes"
          # https://api.github.com/users/megalinter-bot
          GITHUB_ACTOR: megalinter-bot
          GITHUB_ACTOR_ID: 129584137

  msdo:
    permissions:
      contents: read
      id-token: write
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: microsoft/security-devops-action@08976cb623803b1b36d7112d4ff9f59eae704de0 # v1
        id: msdo

      - uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

  trivy-fs:
    permissions:
      contents: write
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.30
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          format: github
          output: dependency-results.sbom.json
          github-pat: ${{ github.token }}

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.30
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,secret,misconfig

      - uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
        with:
          sarif_file: trivy-results.sarif

  trivy-image:
    permissions:
      contents: write
      security-events: write

    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        # required for sarif upload

      - id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          cache-from: ${{ env.GHCR_IMAGE_NAME }}:cache
          load: true

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.30
        with:
          image-ref: ${{ steps.build.outputs.imageid }}
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          format: github
          output: dependency-results.sbom.json
          github-pat: ${{ github.token }}

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.30
        with:
          image-ref: ${{ steps.build.outputs.imageid }}
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-results.sarif

      - uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
        with:
          sarif_file: trivy-results.sarif
